stability:
    roll:
        Kp: 75
        Ki: 0.0
        Kd: 20
        limit: 10
    pitch:
        Kp: 75
        Ki: 0.0
        Kd: 30
        limit: 10
    yaw:
        Kp: 10
        Ki: 0
        Kd: 2000
        limit: 10
    depth:
        Kp: 100
        Ki: 0.0
        Kd: 0