stability:
    roll:
        Kp: 75
        Ki: 0.0
        Kd: 700
        limit: 10
    pitch:
        Kp: 75
        Ki: 0.0
        Kd: 700
        limit: 10
    yaw:
        Kp: 50
        Ki: 0
        Kd: 700
        limit: 10
    depth:
        Kp: 10
        Ki: 0.0
        Kd: 10